#!/bin/sh
awk -v e='' '/menuentry/&&$NF~/[{]/{$NF=e;print "Adding boot "$0}' ${BASH_SOURCE-$0} >&2
exec tail -n +4 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#
# from https://gparted.org/livehd.php
#
menuentry "Gparted live" {
    #set isofile="/home/isos/gparted-live-0.28.1-1-i686.iso"
    set isofile="/gparted-live-1.2.0-1-amd64.iso"
    loopback loop $isofile
    linux (loop)/live/vmlinuz boot=live config union=overlay username=user components noswap noeject vga=788 ip= net.ifnames=0 toram=filesystem.squashfs findiso=$isofile
    initrd (loop)/live/initrd.img
}
